### ISSUE TITLE
Sign in to confirm you're not a bot

### ISSUE THREAD

**Issue by DrNefarius** [codetheweb/muse#1049]
**What's happening?**
With the newest version, I get the message "Sign in to confirm you're not a bot" whenever I try to play a song.
Example command:
`/play query: https://www.youtube.com/watch?v=lgh68Swuak0`

**Logs**
```
  muse Error: Sign in to confirm you’re not a bot
  muse     at privateVideoError (/usr/app/node_modules/@distube/ytdl-core/lib/info.js:91:12)
  muse     at exports.getBasicInfo (/usr/app/node_modules/@distube/ytdl-core/lib/info.js:54:22)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) +552ms
```

**Screenshots**
<img width="230" alt="image" src="https://github.com/user-attachments/assets/55bab297-ecc1-4ffb-8364-15dbe045988e">

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.0
- Docker (if applicable): 26.1.3, build b72abbb
- OS: Ubuntu 20.04.6 LTS

**Comment by Stealthii** [comment]
This is a wider issue affecting many other bots using Youtube's API.

* https://github.com/jagrosh/MusicBot/issues/1588
* https://github.com/play-dl/play-dl/issues/370
* https://github.com/eritislami/evobot/issues/1638
* https://github.com/mps-youtube/yewtube/issues/1276
* https://github.com/ViewTube/viewtube/issues/2935

It seems like the cobalt client implemented OAuth tokens to circumvent this:
https://github.com/imputnet/cobalt/pull/558

Our issue is that [ytsr](https://www.npmjs.com/package/ytsr) (now no longer supported) does not use any OAuth or API tokens for the search requests. One way of tackling this might be to switch out the use of `ytsr` (and `got` possibly) for [@googleapis/youtube](https://www.npmjs.com/package/@googleapis/youtube), utilizing the auth we already have used in other API requests.

**Comment by arty01238** [comment]
I'm also experiencing this issue!

**Comment by kwatman** [comment]
I also have this problem.

**Comment by NYCITGuy** [comment]
I also have this problem! Same configuration

**Comment by MiguelCollado** [comment]
Hi! I'm currently trying to figure it out, based on the comment @Stealthii made. Apparently, there is no issue with @distube/ytsr, (from what I have just tested, the search part is just OK). I think the problem revolves around ytdl instead, when it tries to get the audio stream. 

That ytdl call to fetch for the info has no apiKey whatsoever, so maybe there is an alternative? I dunno, I'll keep trying to solve this issue

**Comment by Fheuef** [comment]
I'm also experiencing this, even when trying to play songs from Spotify weirdly enough

**Comment by MuazAlhaidar** [comment]
Currently experiencing this issue when hosting the Jmusicbot app on PebbleHost
![image](https://github.com/user-attachments/assets/64f97b66-f624-4d9f-a949-5f68eec6e531)

From the Console
[[INFO]] [JMusicBot]: Loaded config from /config.txt
[[INFO]] [Settings]: serversettings.json will be created in /serversettings.json
[[INFO]] [JDA]: Login Successful!
[[INFO]] [WebSocketClient]: Connected to WebSocket
[[INFO]] [JMusicBot]: JMusicBot
[23:27:44] [[INFO]] [JDA]: Finished Loading!
[[ERROR]] [SignatureCipherManager]: Problematic YouTube player script /s/player/<player ID here>/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script<log number here>.js

**Comment by Fheuef** [comment]
Still unable to play anything, though now it does log `WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest"` when requesting a song.

This is using the latest version with Docker Compose so I'm unable to run this before the container starts, will try tomorrow to install it manually.

**Comment by GrantBirki** [comment]
Getting the exact same issue as well

**Comment by Fheuef** [comment]
To add more info here (gathered mostly from the links above), this appears to be an IP block from youtube. Apparently it can even happen because a neighboring IP spammed the youtube API too much.

I can confirm that, while my VPS has been unable to play anything for more than a month, I was able to play songs from both youtube and spotify when running the bot on my own PC.

Some users on other projects were able to access the API with rotating IPv6, cookies from an account that is currently logged in, using a proxy, or with OAuth 2.

I haven't found any workaround that we could use so far, besides running the bot on a entirely different IP.

**Comment by jedichrome** [comment]
Just updated to the latest build and getting this as well.

**Comment by jedichrome** [comment]
I got around this by  making Muse dependant on Warp.

`    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    restart: unless-stopped
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp`

**Comment by karmirith** [comment]
> I got around this by making Muse dependent on [Warp.](https://github.com/cmj2002/warp-docker) Found the workaround here: [jagrosh/MusicBot#1588](https://github.com/jagrosh/MusicBot/issues/1588)
> 
> ```
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     image: caomingjun/warp
>     restart: unless-stopped
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

How do I make this work within my Docker application?

**Comment by jedichrome** [comment]
> How do I make this work within my Docker application?

Just append the about to your docker-compose.yml for Muse and then run docker-compose up -d

In the end it should look similar to this:

```
version: '3.4'

services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN=
      - YOUTUBE_API_KEY=
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
```

**Comment by Nystrata** [comment]
> Just append the about to your docker-compose.yml for Muse and then run docker-compose up -d
> 
> In the end it should look similar to this:
> 
> ```
> version: '3.4'
> 
> services:
>   muse:
>     image: ghcr.io/museofficial/muse:latest
>     restart: always
>     volumes:
>       - ./muse:/data
>     environment:
>       - DISCORD_TOKEN=
>       - YOUTUBE_API_KEY=
>       - SPOTIFY_CLIENT_ID=
>       - SPOTIFY_CLIENT_SECRET=
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     image: caomingjun/warp
>     container_name: warp
>     restart: always
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

I gave that a try and while I am getting video metadata when I /play, the bot doesn't send any audio.
If I remove the warp related settings from the compose, audio does send, for one song. The next one will throw a "sign in to confirm that you're not a bot" again

**Comment by EugeneLeclerc** [comment]
> I got around this by making Muse dependent on [Warp.](https://github.com/cmj2002/warp-docker) Found the workaround here: [jagrosh/MusicBot#1588](https://github.com/jagrosh/MusicBot/issues/1588)

Thanks for the fix! Should we merge this into Muse? The IP-banning from Youtube looks like it will stay, so we need a long term solution.

**Comment by arty01238** [comment]
> > How do I make this work within my Docker application?
> 
> Just append the about to your docker-compose.yml for Muse and then run docker-compose up -d
> 
> In the end it should look similar to this:
> 
> ```
> version: '3.4'
> 
> services:
>   muse:
>     image: ghcr.io/museofficial/muse:latest
>     restart: always
>     volumes:
>       - ./muse:/data
>     environment:
>       - DISCORD_TOKEN=
>       - YOUTUBE_API_KEY=
>       - SPOTIFY_CLIENT_ID=
>       - SPOTIFY_CLIENT_SECRET=
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     image: caomingjun/warp
>     container_name: warp
>     restart: always
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

I can vouch that this works for me! Though I assume they will find a way to implement it into the project overall?

**Comment by Hazzajenko** [comment]
Is this issue still present in muse v2.9.3 or v2.9.4? 

The recent update to @distube/ytdl-core in v2.9.3 has addressed various problems.

**Comment by EugeneLeclerc** [comment]
> Is this issue still present in muse v2.9.3 or v2.9.4?
> 
> The recent update to @distube/ytdl-core in v2.9.3 has addressed various problems.

Yeah, this is not a @distube/ytdl-core issue. Youtube is blocking IPs, there is nothing that can be done on yt-dlp's end, you just have to get an unbanned IP or route your requests through something else (like Warp).

**Comment by EugeneLeclerc** [comment]
> I've tried to set up muse to run with this but the moment I start it with Warp I just get timed out when trying to queue anything. Without warp the bot doesnt time out but I also have the problem of youtube not allowing my connection.

Same for me, Warp worked perfectly for a week, and now I have timeout issues.

**Comment by FeelThePoveR** [comment]
Any idea how to set the warp workaround hosting it on fly.io? I've been using it for quite a while because of it's free tier, but I can't wrap my head around how to configure it.

**Comment by GeorgeGo** [comment]
> > I've tried to set up muse to run with this but the moment I start it with Warp I just get timed out when trying to queue anything. Without warp the bot doesnt time out but I also have the problem of youtube not allowing my connection.
> 
> Same for me, Warp worked perfectly for a week, and now I have timeout issues.

Would moving to using the youtube api without warp work as a solution? I'm running ghcr muse latest as a docker container on digital ocean and it's either "Sign in to confirm you're not a bot" without warp or timeouts with warp.

**Comment by jogerj** [comment]
So far having same issues of "Sign in to confirm you're not a bot" or timeouts with warp. My instance is hosted on Oracle Cloud. 

[yt-dlp has an option to pass cookies.txt](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp), so you can create some dummy account and pass its cookies to access. For us this means the bot needs to be configured to accept and pass the cookies to yt-dlp if configured.

**Comment by tyteen4a03** [comment]
Are there any updates to this?

**Comment by HerIsDia** [comment]
Bug still on in v2.10.0!

**Comment by tyteen4a03** [comment]
> It's not really a bug anymore, if you are experiencing this issue, you either need to change the External IP address or use the warp thing mentioned above and add it to the docker compose file. It's because Google hit you with IP limit on API

Warp didn't work for me, the application just hung instead.

Would appreciate official guidance on this!

**Comment by Happyllama25** [comment]
@tyteen4a03 
I just added the Warp segment on my compose file ~30 mins ago and its working perfectly

**Comment by tyteen4a03** [comment]
> @tyteen4a03 
> I just added the Warp segment on my compose file ~30 mins ago and its working perfectly

Which provider are you on? I'm on Hetzner.

**Comment by Happyllama25** [comment]
> > @tyteen4a03
> > I just added the Warp segment on my compose file ~30 mins ago and its working perfectly
> 
> Which provider are you on? I'm on Hetzner.

Oracle Cloud, I moved my Muse instance to a different node, got the same error, added the Warp dependency and it started working.

If the data center IP has been blacklisted by youtube then there is not that much one can do to unblock.
One could potentially route the traffic via VPN to a household IP.

**Comment by Resonant4949** [comment]
> Oracle Cloud, I moved my Muse instance to a different node, got the same error, added the Warp dependency and it started working.
> 
> If the data center IP has been blacklisted by youtube then there is not that much one can do to unblock. One could potentially route the traffic via VPN to a household IP.

I also run my bot on Oracle Cloud. Unfortunately, Warp does not solve this problem for me permanently. Everything works great for a few hours, but then I get the error message “Sign in to confirm you're not a bot” despite Warp.

**Comment by RooRay** [comment]
For anyone looking at this in the future, looking to implement the WARP solution, breaking changes to the way the container works were introduced by a containerd update in late November, (see [this](https://github.com/cmj2002/warp-docker/blob/main/docs/tun-not-permitted.md)) requiring some light changes. Updated config is this:
```yaml                                                                                    
services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN=YOURS HERE
      - YOUTUBE_API_KEY=YOURS HERE
      # Below are all optional
      # - SPOTIFY_CLIENT_ID=
      # - SPOTIFY_CLIENT_SECRET=
      # - CACHE_LIMIT=10GB
      # - ENABLE_SPONSORBLOCK=true
      # - SPONSORBLOCK_TIMEOUT=2
      # - BOT_STATUS=online
      # - BOT_ACTIVITY_TYPE=LISTENING
      # - BOT_ACTIVITY_URL=   # Not used for non-streaming activity types
      # - BOT_ACTIVITY=your shite music
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      - WARP_LICENSE_KEY=UBW6t134-3A6b24Km-nJ286iN9
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
```
> [!TIP]
> Using a WARP+ key is HIGHLY recommended since you get extra fast bandwidth. If you need a WARP+ key with a bunch of bandwidth, use one from [here](https://casper.wf/100JV.txt).

> [!WARNING]
> If you previously restricted your YouTube Data API key by IP address, this will no longer work. Either remove the restriction or add Cloudflare's IP ranges which are available [here](https://www.cloudflare.com/en-gb/ips/).
