### ISSUE TITLE
unknown error when playing a song

### ISSUE THREAD

**Issue by clragon** [codetheweb/muse#840]
**What's happening?**
When asking the bot to play a song, it fails with `unkown error`. 

**Logs**

```
clragon@fruit:~ $ docker logs ea6f4c815cfa
yarn run v1.22.19
$ npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts

> muse@2.1.7 env:set-database-url
> tsx src/scripts/run-with-database-url.ts

========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 2.1.7 built on 9/20/2022 (commit abdae1a6449d0e3911b45c0dfde3f4b184c17ae0)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


- Applying database migrations...
✔ Database migrations applied.
- 📡 connecting to Discord...
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=XXX&scope=bot%20applications.commands&permissions=XXX
```

**Screenshots**
![th7MNjswyu](https://user-images.githubusercontent.com/11785085/204869330-1dde91d8-46d7-4ba3-9378-fcb28bd37777.png)

**Additional context**
Autocomplete works as normal. 
The bot starts up as normal.
I added `DEBUG=*` to my environment variables, however there do not seem to be any notable things in the logs.

My `docker-compose.yml`:

```yml
version: '3.4'

services:
  muse:
    image: codetheweb/muse:latest
    restart: always
    volumes:
      - ./data:/data
    environment:
      - DISCORD_TOKEN=XXX
      - YOUTUBE_API_KEY=XXX
      - SPOTIFY_CLIENT_ID=XXX
      - SPOTIFY_CLIENT_SECRET=XXX
      - REGISTER_COMMANDS_ON_BOT=true
      - CACHE_LIMIT=512MB
      - DEBUG=*
```

(where as `XXX` replaces my token values)

**Runtime**
I'm running Muse:
- Inside a Docker container

**Versions**
- Muse: 2.1.7
- Docker : 20.10.21, build baeda1f
- OS: Debian GNU/Linux 11 (bullseye) aarch64
