### ISSUE TITLE
Docker Container Infinitely Grows

### ISSUE THREAD

**Issue by coryjreid** [codetheweb/muse#966]
### Problematic Behavior

Something within the Docker container appears to be writing to the container's filesystem causing it to grow infinitely in size, resulting in the container's `overlay2` file to eventually fill the disk.

### Expected Behavior

Container doesn't write to un-mounted directories within the container (or, at least not _continually_).

### Background

This VM only hosts this Docker container and an NGINX server which is a forward-proxy for some streaming URLs that need to remain private and has 32GB of disk space allocated to it.

In the below output you can see me run `du -cs /var/lib/docker/*` back-to-back with a period of only a few seconds between the two and the size of the `overlay2` folder growing in that short time (the bot is actively streaming in Discord). You can also see I only have the one Docker container running.

```
root@muse:/var/lib/docker# du -cs /var/lib/docker/*
108     /var/lib/docker/buildkit
52      /var/lib/docker/containers
4       /var/lib/docker/engine-id
1988    /var/lib/docker/image
52      /var/lib/docker/network
3488800 /var/lib/docker/overlay2
16      /var/lib/docker/plugins
4       /var/lib/docker/runtimes
4       /var/lib/docker/swarm
4       /var/lib/docker/tmp
28      /var/lib/docker/volumes
3491060 total
root@muse:/var/lib/docker# du -cs /var/lib/docker/*
108     /var/lib/docker/buildkit
52      /var/lib/docker/containers
4       /var/lib/docker/engine-id
1988    /var/lib/docker/image
52      /var/lib/docker/network
3489024 /var/lib/docker/overlay2
16      /var/lib/docker/plugins
4       /var/lib/docker/runtimes
4       /var/lib/docker/swarm
4       /var/lib/docker/tmp
28      /var/lib/docker/volumes
3491284 total
root@muse:/var/lib/docker# docker ps -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED        STATUS       PORTS     NAMES
2ee1175cc193   codetheweb/muse:latest   "docker-entrypoint.s…"   22 hours ago   Up 3 hours             muse
root@muse:/var/lib/docker#
```

[This StackOverflow post](https://stackoverflow.com/questions/70354934/docker-overlay2-size-too-big) suggested looking into files being written in the container by running `docker container diff <container_name/id>`, which I did, and you can see the output [here](https://gist.github.com/coryjreid/e9e20df5d052023b75635a192382776d).

For the sake of completeness, my compose file is:
```
version: '3.4'

services:
  muse:
    container_name: muse
    image: codetheweb/muse:latest
    restart: always
    network_mode: host # allows access to NGINX proxy on same VM
    volumes:
      - ./data:/data
    environment:
      - DISCORD_TOKEN=***
      - YOUTUBE_API_KEY=***
      - SPOTIFY_CLIENT_ID=***
      - SPOTIFY_CLIENT_SECRET=***
```
